# Generated by Django 5.1.1 on 2024-09-06 06:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                ("date_created", models.DateField()),
            ],
        ),
    ]
