# Generated by Django 5.1.1 on 2024-09-09 06:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="date_created",
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
